name: docs
channels:

  - conda-forge

  - defaults
dependencies:
    # Base depends
  - python
  - pip
  - pytorch
  - jax
  - networkx
  - numpyro
  - numpy
  - pint

    # Pip-only installs
  #- pip:
  #  - codecov

